# specify device on which the model is trained
device: cuda

# set to 'None' if a new model should be trained, otherwise specify
# a model's directory
evaluation: None

# define the dataset arguments
dataset_args:
  window_size: 30

# define the dataloader arguments
dataloader_args:
  batch_size: 4
  num_workers: 1
  shuffle: True

# define the model by setting its class name here, do
# not forget to register it in utils/config.py
model_name: Multimodal_v1

# set the amount of epochs to train and specify intermediate
# savings
train_epochs: 50
save_every: 10

# configure the model
model_args:
  tag: Multimodal_v1/ws_30/lstm_2
  log: True
  lr: 0.001
  momentum: 0.9
  lr_decay: 0.98
  weight_decay: 0.01
  dropout: 0.1
  resnet: True
  lstm_layers: 2
  lstm_hidden: 128
