# specify device on which the model is trained
device: cuda

# set to 'None' if a new model should be trained, otherwise specify
# a model's directory
evaluation: None

# define the dataset arguments
dataset_args:
  window_size: 60

# define the dataloader arguments
dataloader_args:
  batch_size: 16
  num_workers: 1
  shuffle: True

# define the model by setting its class name here, do
# not forget to register it in utils/config.py
model_name: Multimodal_v1

# set the amount of epochs to train and specify intermediate
# savings
train_epochs: 15
save_every: 5

# configure the model
model_args:
  tag: Multimodal_v1/default
  log: True
  lr: 0.003
  lr_decay: 0.9
  weight_decay: 0.05
  resnet: True
  lstm_layers: 2
  lstm_hidden: 128
